package:
  name: sstmap
  version: 1.1.4

source:
  path: ../../


requirements:
  build:
    - python
    - numpy 1.14.*
    - setuptools
    - gcc
    - toolchain3
    - libgcc
    - gsl 2.2.*
    - libopenblas

  run:
    - python
    - libgcc
    - numpy 1.14.*
    - scipy
    - mdtraj
    - parmed
    - matplotlib
    - gsl 2.2.*
    - libopenblas

#test:
#  commands:
#    - run_gist -h
#    - run_hsa -h
#  imports:
#    - sstmap

about:
  home: https://github.com/KurtzmanLab/SSTMap
  license: MIT
  summary: Python tools for analysis of water molecules in MD trajectories.

