package:
  name: sstmap
  version: 1.1.0

source:
  path: ../../


requirements:
  build:
    - python
    - numpy 1.11.*
    - setuptools
    - gcc
    - toolchain

  run:
    - python
    - libgcc
    - numpy
    - scipy
    - mdtraj
    - parmed
    - matplotlib

test:
  commands:
    - run_gist -h
    - run_hsa -h
  imports:
    - sstmap

about:
  home: https://github.com/kamran-haider
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Python tools for analysis of water molecules in MD trajectories.

